MVCW1App/Models/Product.cs
namespace MVCW1App.Models
{
    public class Product
    {
        public int ProductId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public string Category { get; set; }
    }
}

MVCW1App/Models/ViewModels/ProductsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MVCW1App.Models;

namespace MVCW1App.Models.ViewModels
{
    public class ProductsViewModel
    {
        public IEnumerable<Product> Products { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentCategory { get; set; }
    }
}

MVCW1App/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using MVCW1App.Models;
using Microsoft.EntityFrameworkCore;

namespace MVCW1App.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private AppDbContext context;
        public NavigationMenuViewComponent(AppDbContext ctx)
        {
            context = ctx;
        }
        public IViewComponentResult Invoke()
        {
            var Products = context.Products.FromSql("GetAllProducts").ToArray();

            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x));
        }
    }
}

MVCW1App/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MVCW1App.Models;
using MVCW1App.Models.ViewModels;
using Microsoft.EntityFrameworkCore;

namespace MVCW1App.Controllers
{
    public class HomeController : Controller
    {
        private readonly AppDbContext context;

        public int PageSize = 4;

        public HomeController(AppDbContext ctx)
        {
            context = ctx;
        }

        public IActionResult Index() => View();

        public ViewResult Products(string category, int page = 1)
        {            
            var Products = context.Products.FromSql("GetAllProducts").ToArray();
            
            return View(new ProductsViewModel
            {
                Products = Products
               .Where(p => category == null || p.Category == category)
               .OrderBy(p => p.ProductId)
               .Skip((page - 1) * PageSize)
               .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ? Products.Count() : Products.Where(e => e.Category == category).Count()
                },
                CurrentCategory = category
            });
        }
      
        public IActionResult Contacts() => View();


        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCW1App/Views/Home/Contacts.cshtml
@{
    ViewData["Title"] = "Contact";
}
<div class="container">
    <h2>@ViewData["Title"]</h2>
    <h3>@ViewData["Message"]</h3>
    <address>
        <strong>Support:</strong> <a href="mailto:CrimeanOM@Outlook.com">CrimeanOM@outlook.com</a><br />
    </address>
</div>

MVCW1App/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}
<div class="container">
    <h4>Todo list</h4>
    <ul class="list-unstyled">
        <ul>
            <li class="text-success">Product's catalog (Recomended)...done</li>
            <li class="text-success">Manager controller Product's CRUD...done</li>
            <li class="text-success">Products pagination (Recomended)...done</li>
            <li class="text-success">Cart with CRUD (Recomended)...done</li>
            <li class="text-success">Pay via W1 (Recomended)...done</li>
            <li class="text-success">Implement database interaction through stored procedures...done</li>
        </ul>
    </ul>
</div>

MVCW1App/Views/Home/Products.cshtml
@model ProductsViewModel
@{
    ViewData["Title"] = "Products";
}
<div class="row">
    <div id="categories" class="col-md-2">
        @await Component.InvokeAsync("NavigationMenu")
    </div>

    <div class="container col-md-9">
        @foreach (var product in Model.Products)
        {
            @Html.Partial("ProductSummary", product)
        }
        <div page-model="@Model.PagingInfo" page-action="Products" page-classes-enabled="true" page-class="btn" page-class-normal="btn-outline-dark"
             page-class-selected="btn-dark" page-url-category="@Model.CurrentCategory" class="btn-group-sm pull-right">
        </div>
    </div>
</div>