MVCW1App/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MVCW1App.Models;

namespace MVCW1App.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke() => View(cart);
    }
}

MVCW1App/Controllers/CartController.cs
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MVCW1App.Infrastructure;
using MVCW1App.Models;
using MVCW1App.Models.ViewModels;
using Microsoft.EntityFrameworkCore;

namespace MVCW1App.Controllers
{
    public class CartController : Controller
    {
        private AppDbContext context;
        private Cart cart;
        public CartController(AppDbContext ctx, Cart cartService)
        {
            context = ctx;
            cart = cartService;
        }
        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }
        public RedirectToActionResult AddToCart(int productId, string returnUrl)
        {
            System.Data.SqlClient.SqlParameter param1 = new System.Data.SqlClient.SqlParameter("@productId", $"{productId}");
            var product = context.Products.FromSql("GetProduct @productId", param1).ToList().FirstOrDefault();
            if (product != null)
                cart.AddItem(product, 1);
            
            return RedirectToAction("Index", new { returnUrl });
        }
        public RedirectToActionResult RemoveFromCart(int productId, string returnUrl)
        {
            System.Data.SqlClient.SqlParameter param1 = new System.Data.SqlClient.SqlParameter("@productId", $"{productId}");
            var product = context.Products.FromSql("GetProduct @productId", param1).ToList().FirstOrDefault();
            if (product != null)
                cart.RemoveLine(product);
            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

MVCW1App/Views/Shared/ProductSummary.cshtml
@model Product
<h5>@Model.Name @Model.Price.ToString("c")</h5>
<form id="@Model.ProductId" asp-action="AddToCart" asp-controller="Cart" method="post">
    <input type="hidden" asp-for="ProductId" />
    <input type="hidden" name="retutnUrl" value="@ViewContext.HttpContext.Request.Path" />
    <span class="lead">
        @Model.Description
        <button type="submit" class="btn btn-success btn-sm pull-right">
            Add To Cart
        </button> 
    </span>
</form>
<br/>

MVCW1App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="2hfp1SzUoho7/TsGGGDaFdsuuDL0LX2hnUp6VkX3CUQ2K4K+xjboZdsXyp4oUHZj" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#togler" aria-controls="togler" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon small"></span>
        </button>
        <a class="navbar-brand" asp-action="Index" asp-controller="Home">Wallet One Test App</a>
        <div class="collapse navbar-collapse mr-auto" id="togler">
            <div class="navbar-nav" align="center">
                <a class="nav-item nav-link" asp-controller="Home" asp-action="Index">Main</a>
                <a class="nav-item nav-link" asp-controller="Home" asp-action="Products">Products</a>
                <a class="nav-item nav-link" asp-controller="Home" asp-action="Contacts">Contacts</a>
            </div>
        </div>
        <div class="pull-right">
            @await Component.InvokeAsync("CartSummary")
        </div>
        <div>
            <a class="btn btn-outline-light btn-sm navbar-btn" asp-controller="Cart" asp-action="Index" asp-route-returnurl="@ViewContext.HttpContext.Request.PatgAndQuery()">
                <i class="fa fa-shopping-cart"></i>
            </a>
        </div>
    </nav>

        <br />
            <div class="col-xs-8">
                @RenderBody()
            </div>

   
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="VjEeINv9OSwtWFLAtmc4JCtEJXXBub00gtSnszmspDLCtC0I4z4nqz7rEFbIZLLU" crossorigin="anonymous"></script>

        <footer>
            <div class="label" align="center">
                Source code: <a href="https://gitlab.com/CrimeanOM/MVCW1App">GitLab</a>
            </div>
        </footer>
</body>
</html>