MVCW1App/Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVCW1App.Models;

namespace MVCW1App.Controllers
{
    public class ManagerController : Controller
    {
        private readonly AppDbContext context;
        public ManagerController(AppDbContext ctx)
        {
            context = ctx;
        }
        public IActionResult Index()
        {
            var products = context.Products.FromSql("GetAllProducts").ToArray();
            return View(products);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Product product)
        {
            System.Data.SqlClient.SqlParameter param1 = new System.Data.SqlClient.SqlParameter("@category", $"{product.Category}");
            System.Data.SqlClient.SqlParameter param2 = new System.Data.SqlClient.SqlParameter("@description", $"{product.Description}");
            System.Data.SqlClient.SqlParameter param3 = new System.Data.SqlClient.SqlParameter("@name", $"{product.Name}");
            System.Data.SqlClient.SqlParameter param4 = new System.Data.SqlClient.SqlParameter("@price", $"{product.Price}");
            context.Database.ExecuteSqlCommand("InsertIntoProducts @category, @description, @name, @price", param1, param2, param3, param4);
            await context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Edit(int? productId)
        {
           if (productId != null)
            {
                System.Data.SqlClient.SqlParameter param1 = new System.Data.SqlClient.SqlParameter("@productId", $"{productId}");
                var product = context.Products.FromSql("GetProduct @productId", param1).ToList().FirstOrDefault();
                if (product != null)
                    return View(product);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Product product)
        {
            System.Data.SqlClient.SqlParameter param1 = new System.Data.SqlClient.SqlParameter("@productId ", $"{product.ProductId}");
            System.Data.SqlClient.SqlParameter param2 = new System.Data.SqlClient.SqlParameter("@category", $"{product.Category}");
            System.Data.SqlClient.SqlParameter param3 = new System.Data.SqlClient.SqlParameter("@description", $"{product.Description}");
            System.Data.SqlClient.SqlParameter param4 = new System.Data.SqlClient.SqlParameter("@name", $"{product.Name}");
            System.Data.SqlClient.SqlParameter param5 = new System.Data.SqlClient.SqlParameter("@price", $"{product.Price}");
            context.Database.ExecuteSqlCommand("EditProduct @productId, @category, @description, @name, @price", param1, param2, param3, param4, param5);
            await context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int? productId)
        {
            if (productId != null)
            {
                System.Data.SqlClient.SqlParameter param1 = new System.Data.SqlClient.SqlParameter("@productId", $"{productId}");
                var product = context.Products.FromSql("GetProduct @productId", param1).ToList().FirstOrDefault();
                if (product != null)
                {
                    context.Database.ExecuteSqlCommand("RemoveProduct @productId", param1);
                    await context.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            return NotFound();
        }
    }
}

MVCW1App/Views/Manager/Create.cshtml
@model Product
@{
    ViewData["Title"] = "Adding new product";
}
<div class="container">
    <div asp-validation-summary="All"></div>
    <form asp-action="Create" asp-controller="Manager">
        <div class="form-group">
            <label for="Name"></label>
            <br />
            <input type="text" class="form-control" id="Name" aria-describedby="titleHelp" placeholder="Enter the product name" asp-for="Name" />
        </div>

        <div class="form-group">
            <label for="Description"></label>
            <br />
            <input type="text" class="form-control" id="Description" aria-describedby="descriptionHelp" placeholder="Enter the product description" asp-for="Description" />
        </div>
        <div class="form-group">
            <label for="Category"></label>
            <br />
            <input type="text" class="form-control" id="Category" aria-describedby="categoryHelp" placeholder="Enter the product category" asp-for="Category" />
        </div>
        <div class="form-group">
            <label for="Price"></label>
            <br />
            <input type="text" class="form-control" id="Price" aria-describedby="priceHelp" placeholder="Enter the product price" asp-for="Price" />
        </div>
        <div>
            <input class="btn btn-outline-dark" type="submit" value="Add" />
            <a asp-action="Index" asp-controller="Home" class="btn btn-outline-danger">Cancel</a>
        </div>
    </form>
</div>

MVCW1App/Views/Manager/Delete.cshtml
@model Product
@{
    ViewBag.Title = "Deleting product";
}
<div>
    <dl class="dl-horizontal">
        <dt>Name</dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>Description</dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>Category</dt>
        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

        <dt>Price</dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>

    <div>
        <form asp-controller="Manager" asp-action="Delete" asp-route-projectId="@Model.ProductId" method="post">
            <div class="form-group">
                <input type="submit" class="btn btn-outline-dark btn-sm" value="Remove" />
            </div>
        </form>
    </div>
</div>

MVCW1App/Views/Manager/Edit.cshtml
@model Product
@{
    ViewBag.Title = "Edit product";
}
<div class="container">
    <form asp-action="Edit" asp-controller="Manager" asp-route-projectId="@Model.ProductId">
        <input type="hidden" id="Id" asp-for="@Model.ProductId" />
        <div class="form-group">
            <label for="Name"></label>
            <br />
            <input type="text" class="form-control" id="Name" aria-describedby="titleHelp" placeholder="Enter the product name" asp-for="Name" />
        </div>
        <div class="form-group">
            <label for="Description"></label>
            <br />
            <input type="text" class="form-control" id="Description" aria-describedby="descriptionHelp" placeholder="Enter the product description" asp-for="Description" />
        </div>
        <div class="form-group">
            <label for="Category"></label>
            <br />
            <input type="text" class="form-control" id="Category" aria-describedby="categoryHelp" placeholder="Enter the product category" asp-for="Category" />
        </div>
        <div class="form-group">
            <label for="Price"></label>
            <br />
            <input type="text" class="form-control" id="Price" aria-describedby="priceHelp" placeholder="Enter the product price" asp-for="Price" />
        </div>
        <div>
            <input class="btn btn-outline-dark" type="submit" value="Save" />
            <a asp-action="Index" class="btn btn-outline-danger">Cancel</a>
        </div>
    </form>
</div>

MVCW1App/Views/Manager/Index.cshtml
@model IEnumerable<Product>
@{
    ViewBag.Title = "Manage products";
}
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Category</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var prod in Model)
            {
                <tr>
                    <td>@prod.Name</td>
                    <td>@prod.Description</td>
                    <td>@prod.Category</td>
                    <td>@prod.Price</td>
                    <td>
                        <form method="post">
                            <a class="btn btn-outline-dark btn-sm" asp-action="Edit" asp-controller="Manager" asp-route-productId="@prod.ProductId">Edit</a>
                            <button class="btn btn-outline-danger btn-sm" asp-action="Delete" asp-controller="Manager" asp-route-productId="@prod.ProductId">Remove</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <br />
    <a class="btn btn-outline-dark" asp-action="Create">Add new product</a>
    <a class="btn btn-outline-danger" asp-action="Index" asp-controller="Home">Cancel</a>
</div>